DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT
(ID LONG AUTO_INCREMENT PRIMARY KEY NOT NULL,
ACCOUNT_TYPE VARCHAR(255) NOT NULL DEFAULT '',
BALANCE DOUBLE NOT NULL DEFAULT 0.00,
ACCOUNT_NUMBER LONG NOT NULL DEFAULT 000000000,
USER_ID LONG NOT NULL);

INSERT INTO ACCOUNT(ACCOUNT_TYPE, BALANCE, ACCOUNT_NUMBER, USER_ID)
VALUES('Checking', 123.45, 987654321, 23);