@startuml
'https://plantuml.com/sequence-diagram
Class User {
@PrimaryID Long ID
@Entity
UserInfo;
ThreeAccounts;
}
Class UserInfo {
firstName
lastName
Email
PhoneNumber
Address
Occupation
UserName
Password
}
Class ThreeAccounts {
CheckingAccount;
SavingsAccount;
InvestmentAccount;
}
Abstract Class Account {
AccountNumber;
Balance;
}
Class CheckingAccount {
AccountNumber;
Balance;
}
Class SavingsAccount {
AccountNumber;
Balance;
}
Class InvestmentAccount {
AccountNumber;
Balance;
}

Class Login {
CheckIfValidInputUserName();
CheckIfValidInputPassword();
CreateAccount();
Help();
}

'Maybe a UserController - createUser(), UpdateUser(), DeleteUser(),

Class UserController {
CreateUser();
UpdateUser();
'UpdateAccount();
'DeleteAccount();
DeleteUser();
}
Class UserService {
Create();
findById(@PathVariable Long id);
}
Interface UserRepository {
implements CrudRepository;
}

Class AccountController {
PUTWithdraw(@PathVariable AccountNumber, double amount);
PUTTransfer(@PathVariable AccountNumberOne, @PathVariable AccountNumberTwo, double amount);
PUT Deposit(@PathVariable AccountNumber, double amount);
POST CreateAccount(Long AccountNumber, double balance);
GET GetBalance();
}
Class AccountService {
UpdateBalance();
createAccount();
}
Interface AccountRepository {
implements CrudRepository;
}

Class AccountFactory {
GenerateAccountNumber(UserId, firstName);
}

Account <|-- CheckingAccount
Account <|-- SavingsAccount
Account <|-- InvestmentAccount

UserRepository <|-- UserService
UserService <|-- UserController

AccountRepository <|-- AccountService
AccountService <|-- AccountController
@enduml